server:
  port: 8259

eureka:
  instance:
    namespace: eureka02.com
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://eureka01.com:8260
