server:
  port: 8080

spring:
  application:
    name: MALL-WEB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8260/eureka

feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
